language: java
jdk:
  - openjdk8

# push될 떄 수행할 브랜치 설정
#branches:
#  only:
#    - master
#    - develop

# Travis CI Server Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

# push 되었을때 수행하는 명령어
# 해당 명령어는 gradlew를 통해 clean & build를 수행
script: "./gradlew clean build"

before_deploy:
  - zip -r geongoo *
  - mkdir -p deploy
  - mv geongoo.zip deploy/geongoo.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY # Travis repo settings에 설정된 값
    secret_access_key: $AWS_SECRET_KEY # Travis repo settings에 설정된 값
    bucket: geongoo-deploy
    key: geongoo.zip
    bundle_type: zip
    application: geongoo
    deployment_group: geongoo-group
    region: ap-northeast-2
    skip_cleanup: true
    acl: public_read
    local_dir: deploy # before_deploy에서 생성한 디렉토리
    wait-until-deployed: true
    on:
      repo: JeonGoo/JeonGoo_Server #Github 주소
      branch: develop

# Tarvis CI 실행 완료시 자동으로 알림이 가도록 설정
# CI 실행 완료시 메일로 알람
notifications:
  email:
    recipients:
      - bkh115819@gmail.com
