language: java
jdk:
  - openjdk8

# push될 떄 수행할 브랜치 설정
branches:
  only:
    - develop

# Travis CI Server Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

# push 되었을때 수행하는 명령어
# 해당 명령어는 gradlew를 통해 clean & build를 수행
script: "./gradlew clean build"

# Tarvis CI 실행 완료시 자동으로 알림이 가도록 설정
# CI 실행 완료시 메일로 알람
notifications:
  email:
    recipients:
      - bkh115819@gmail.com