spring:
  profiles:
    active: develop
    include:
      - db

---
spring:
  profiles: local
  datasource:
    url: jdbc:h2:tcp://localhost/~/jeongoo
    username: sa
    password:
    driver-class-name: org.h2.Driver
    platform: test
    initialization-mode: always

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100
    open-in-view: false

  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 1000
